### ISSUE TITLE
Mod crashes with no report being created.

### ISSUE THREAD

**Issue by MagmaSlime123** [Prospector/ModMenu#106]
There's not much I can do. Only thing I'm given is this. No crash report file is being created.

![image](https://user-images.githubusercontent.com/51277766/79048836-9d443e80-7bd4-11ea-95e3-7248717ae76e.png)

Latest Fabric API and Fabric Loader, along with these mods, which are also fully updated.
(REI doesn't cause issues without this mod, even though it says unstable. It's only this 
mod that causes this issue.)

![image](https://user-images.githubusercontent.com/51277766/79048874-dc728f80-7bd4-11ea-88e4-3455bb5e0760.png)

**Comment by Prospector** [comment]
You were using a pretty old version, that's probably why it crashed. The latest version supports 20w17a

**Comment by MagmaSlime123** [comment]
You responded 12 days later, that's why this was outdated...

**Comment by Prospector** [comment]
At the time your version was already outdated. In your screenshot you show using v1.10.0, which is a 1.15.2 build from early February, when it looks like from your screenshot that you were trying to use it on 20w15a, which Mod Menu had a build for since March 30th (almost 2 weeks before your issue was posted, https://www.curseforge.com/minecraft/mc-mods/modmenu/files/2916534)
