### ISSUE TITLE
Disable Mod Configuration Button

### ISSUE THREAD

**Issue by ghost** [Prospector/ModMenu#117]
For this modpack I'm creating, I don't want other people to try to configure the mod configs in-game as it may break something in the game. Maybe an option to disable in-game configuration?

**Comment by Prospector** [comment]
I may still add this, but personally IMO if your modpack isn't a kitchen sink pack and it would be ruined if people added, removed, or configured mods, then it probably shouldn't have Mod Menu in it.

**Comment by Madis0** [comment]
Why include Mod Menu to the mod pack in the first place then? Considering most mod packs list the mods and versions in their website anyway.

Edit: to be clear, this comment was made without seeing the comment published 1 min before.

**Comment by Prospector** [comment]
Personally, if I made a pack that was highly customized and integrated, I would never include Mod Menu because I would see the pack as a cohesive product, and not a collection of parts. Whereas, if it's just someone throwing a bunch of mods together, then the mods are the content, not the modpack itself, so Mod Menu would be included so people can see and configure the mods to their liking.
