### ISSUE TITLE
Detect unmarked APIs

### ISSUE THREAD

**Issue by Madis0** [Prospector/ModMenu#140]
You recently added a feature to automatically detect client-side mods in #134, could it be possible to also detect APIs the similar way? As an example, Mod Menu claims I have 30 mods, but 4 of them seem to be just unmarked APIs:

![image](https://user-images.githubusercontent.com/8611110/87676050-cd295200-c780-11ea-968a-c8657be53efa.png)

**Comment by Siphalor** [comment]
Most of them are actually jijed non-mod dependencies.
On the discord was brought up that Fabric Loader treats them the same as normal mods.

So it would probably be hard to detect that.

Probably ask the mod authors that include these mods to mark them properly or shadow them instead of jijing them.

**Comment by Prospector** [comment]
Unfortunately this is sorta on loom I believe. It generates the fabric.mod.jsons for these deps, and it needs to include some way to distinguish them with a custom element or something.

**Comment by uiytt** [comment]
> Unfortunately this is sorta on loom I believe. It generates the fabric.mod.jsons for these deps, and it needs to include some way to distinguish them with a custom element or something.

Still no solution to that from fabric ?

**Comment by altrisi** [comment]
Since a recent loom commit those are now detectable with the `fabric-loom:generated:true` custom property.
See FabricMC/fabric-loom#271.

**Comment by Prospector** [comment]
Added in v1.14.7
