### ISSUE TITLE
Delete mods

### ISSUE THREAD

**Issue by Madis0** [Prospector/ModMenu#144]
Well, we can drag mods into the menu now, but what if we could also delete them from there? 
For mod updates you could even detect if it is the same mod to automatically remove the older version.

**Comment by Prospector** [comment]
I think for now, I'm going to consider this out of scope since it's non-trivial to get this to work on all operating systems. If anyone does know of a fairly simple way to get this working on all operating systems and if it isn't very fragile or anything, perhaps it will be considered again in the future.
