### ISSUE TITLE
Hard dependency on ModMenu?

### ISSUE THREAD

**Issue by kotx** [Prospector/ModMenu#147]
Is there a way to implement ModMenu, but not require it? I'd assume this would be possible if info is just included in fabric.mod.json, but I'm using a custom config screen through ModMenuApi.

**Comment by Linguardium** [comment]
by default you can do this via modImplementation/modApi without using the include.
Your ModMenuApi class should not initialize unless modmenu is present (just dont reference it from your code anywhere).

Make sure to add modmenu's id to the fabric.mod.json (not in depends, that would force them to have it, put it in suggests instead)
you would also need the modmenu entrypoint so that modmenu, if loaded, can find your class.

edit: i just realized that you may have meant "how do you use modmenu but not require players to download it"
in this case, you add the include line to your build.gradle, copy the modImplementation/modApi path you use to add it to your project. This will Jar-in-Jar modmenu into your mod and include modmenu in every release.

**Comment by kotx** [comment]
I meant the former; thanks.
