### ISSUE TITLE
Can't drag and drop files into mod menu

### ISSUE THREAD

**Issue by cocorobot3** [Prospector/ModMenu#226]
I can't drag and drop the mods from my mod folder into the mod menu. I've tried restarting my computer with no avail. 

![Screenshot 2021-03-02 095329](https://user-images.githubusercontent.com/72717520/109676164-0d85e680-7b3e-11eb-99a6-96c6a7a525da.png)

I am trying to download the "Aether Mod" but it still refuses to work. I'm not sure if this is a bug with the ModMenu or a bug with my computer?

**Comment by cocorobot3** [comment]
I thought I fixed it because the game version was weird, but no it still doesn't work

**Comment by Prospector** [comment]
You're trying to install a Forge 1.7.10 mod and a Forge 1.12.2 mod into a Fabric 1.16.5 environment. That's not going to work for multiple reasons:
1. Forge mods are not compatible with Fabric
2. 1.7.10 mods are not compatible with 1.16.5
3. 1.12.2 mods are not compatible with 1.16.5

In addition, those mods are already in your mods folder, so even if they were valid 1.16.5 Fabric mods, dragging and dropping them would be pointless because they're already in the right spot.
