### ISSUE TITLE
Clashes with wurst client

### ISSUE THREAD

**Issue by Savagent** [Prospector/ModMenu#256]
The alt manager feature on wurst clashes with the mods button
https://imgur.com/zXhK1UA

**Comment by K0-RR** [comment]
This is more of the Wurst issue I think and it is reported https://github.com/Wurst-Imperium/Wurst7/issues/291
You can switch to the "replace realms button" mode.
![image](https://user-images.githubusercontent.com/43277609/118396881-d8c00080-b651-11eb-9e3a-7d7d723959e9.png)

The real issue is you can't open the ModMenu list while in the world
![image](https://user-images.githubusercontent.com/43277609/118396917-fbeab000-b651-11eb-97b0-85b156bf8f8a.png)
