### ISSUE TITLE
1.17.1 Crash: "mouseClicked event handler"

### ISSUE THREAD

**Issue by syeare** [Prospector/ModMenu#359]
I can play the game and access most ModMenu's fine, but I can't access the configuration of 2 mods from the Mod menu. Everything else works fine. Specifically, DynSFX 1.5.0 (https://gitlab.com/mikenrafter1/mc-dyn-sfx/-/releases/1.5.0) and FabriShot (https://www.curseforge.com/minecraft/mc-mods/fabrishot). The moment I click, it crashes. NEC tells me it's possibly the fault of Cloth Config v4 or Mod Menu. Is there any other info I can list? I don't use any mods that are in beta or unstable so idk the problem

**Crash log**
https://gist.github.com/syeare/00eb1c8f428b3ff2863a1cbf957b4ec8

**Comment by jackassmc** [comment]
This crash is caused by DynSFX 1.5.0 bundling an outdated Cloth Config. To resolve this issue install the latest Cloth Config ([Curseforge](https://www.curseforge.com/minecraft/mc-mods/cloth-config/files/)). I am able to open the config screens of both DynSFX 1.5.0 and FabriShot 1.5.1 with Cloth Config 5.0.34.

Please also report this issue to the DynSFX maintainers.

**Comment by syeare** [comment]
I can confirm that after updating Cloth Config (to v5.0.38), DynSFX and FabriShot works. Thanks!
