### ISSUE TITLE
Make words like Minecraft, CurseForge, Discord, Modrinth untranslatable

### ISSUE THREAD

**Issue by K0-RR** [Prospector/ModMenu#400]
It doesn't make sense to have them on weblate. Unless someone translates these words manually and then dismisses all the checks they are the reason translations progress is lower than it should be e.g. 90% instead 100%.

> Twitter, Twitch, Patreon, Open Collective, Ko-fi, Liberapay, Flattr, YouTube, Crowdin, Buy Me a Coffee, Coindrop.

**Comment by Madis0** [comment]
In some languages they could be transliterated (rewritten with a different alphabet) and some languages they may even have a translation. Not sure what a good solution would be here to hide them from most languages.

**Comment by jackassmc** [comment]
Since some languages benefit from having those words being translatable and it is possible to dismiss the check they'll stay translatable.

If non admin Weblate users are able to dismiss this check for all languages (checkmark next to the dismiss button) feel free to do that, the strings stay translatable regardless of that check.
