### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by SAJewers** [Prospector/ModMenu#612]
edit; wrong crash log, see below
Reverting to 7.0.1 works

**Comment by LostLuma** [comment]
Seems like it's an issue with the smooth swapping mod: https://github.com/Schauweg/Smooth-Swapping/issues/57

**Comment by SAJewers** [comment]
oops, I posted the wrong crash log
[crash-2023-06-17_19.40.33-client.txt](https://github.com/TerraformersMC/ModMenu/files/11781168/crash-2023-06-17_19.40.33-client.txt)
this is the right one

**Comment by LostLuma** [comment]
That's an issue with [slight GUI modifications](https://github.com/shedaniel/slight-gui-modifications) trying to change how the modmenu renders, which has changed.

You can see which mod causes the error in the traceback:
`Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [#slight-gui-modifications:slight-gui-modifications.mixins.json:modmenu.MixinModsScreen from mod slight-gui-modifications]`

**Comment by SAJewers** [comment]
Yep, and it looks like they already know and fixed it: https://github.com/shedaniel/slight-gui-modifications/issues/96
