### ISSUE TITLE
a problem when the "badge" of the mod is empty

### ISSUE THREAD

**Issue by EliSATfe** [Prospector/ModMenu#736]
I was using the mod menu to manage my mods and then the game crashed.
The log shows a reason

Caused by: java.lang.NullPointerException: Cannot invoke "com.terraformersmc.modmenu.util.mod.Mod$Badge.getText()" because "badge" is null

[Output before game crash.txt](https://github.com/user-attachments/files/15521113/default.txt)

**Comment by haykam821** [comment]
From what I can tell, the file you've attached is empty. Could a list of mods be posted? Having the mod list would help to better track down the mod that causes the issue.

The source of the issue here is described in #693, and there is a pull request open to fix the issue. The ideal behavior is for Mod Menu to not crash, but one of the other mods you have installed is specifying an unknown badge.

**Comment by EliSATfe** [comment]
Sorry for the late reply. I noticed that there may have been an error while loading a plugin mod for Meteor
[mod list.txt](https://github.com/user-attachments/files/15747609/mod.list.txt)

**Comment by haykam821** [comment]
[Version 9.2.0](https://github.com/TerraformersMC/ModMenu/releases/tag/v9.2.0) should fix this issue. The mod that has an unknown badge will be listed in the game logs.
