### ISSUE TITLE
no mod button on title screen

### ISSUE THREAD

**Issue by brunotron** [Prospector/ModMenu#783]
A few days ago I installed the "4Jlegacy" mod and I was having fun but I got tired of it and I got rid of it but when I opened my game the mod button was gone and it can only be shown in the pause menu and I'm tried to get it back but it didn't work
please help with this problem. thank you!
![Screenshot 2024-09-29 at 4 48 36 p m](https://github.com/user-attachments/assets/cacd9951-719a-4e0f-a1b9-5cbd7364ec6f)
![Screenshot 2024-09-29 at 4 50 43 p m](https://github.com/user-attachments/assets/93fc566d-74bb-4f06-9167-ab2286219ef9)
![Screenshot 2024-09-29 at 4 51 58 p m](https://github.com/user-attachments/assets/2c2a3ee3-3e0d-4561-be2b-4f2d4b590d69)

**Comment by brunotron** [comment]
I JUST WANTED SOME HELP, IS THAT TOO MUCH TO ASK!?

**Comment by gniftygnome** [comment]
Maybe check the config file?  Something like `config/modmenu.json`.  Check whether `modify_title_screen` is still set to true?  Or just delete the config file and restart Minecraft.

Otherwise I think we should probably start with the log so we can see what's actually running and whether any errors are logged.

**Comment by brunotron** [comment]
okay, thanks!
sorry for that😣

**Comment by brunotron** [comment]
EEEEEEEEEEEEEEEEEEE
THANK YOUUUUUUUUUUUUU❤️
